spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 80MB
      max-request-size: 80MB
  datasource:
    password: 111111
    username: root
    url: jdbc:mysql://localhost:3306/nbjyj_zzzlxt?&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   这些配置和上面的配置不同，下面的这些配置不是直接在yml加上就能立刻使用，而是要配置bean加入ioc容器才能使用
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   用于阿里相应客户端的可视化操作，用于查看数据库的相关信息，去掉后这一段配置监控界面无法统计相应的数据库
#   操作信息，'wall'用于防火墙操作
    filters: stat,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 项目启动的时候，会自动创建sql语句
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
mybatis:
  #想要配置文件生效就要扫描后加入bean
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      file-date-format: _yyyy-MM-dd
      prefix: tomcatLog
      directory: C:/logs
      #log_时间 远程主机名 远程ip地址 本地ip地址 请求方式 请求方法 url 请求端口 响应码 sessionId 处理时间 当前线程名 返回数据字节数
      pattern: log_%t %h %a %A %H %m %U %p %s %S %T %I %b $remote_user
    max-http-post-size: 10MB
  # 下面这个参数是为解决问题而新增
  max-http-header-size: 8192
  # servlet:
  #  context-path: /spring

  #tomcat:
  # port-header:
  address: 0.0.0.0
  servlet:
    session:
      timeout: 3600s